<?xml version="1.0" encoding='UTF-8' ?>
<!DOCTYPE university [

<!ELEMENT university (faculty+)>
<!ELEMENT faculty (department+)>
<!ELEMENT department (group+)>
<!ELEMENT group (student+)>
<!ELEMENT student (EMPTY)>

<!ATTLIST university name CDATA #FIXED "НИЯУ МИФИ">
<!ATTLIST faculty name (КиБ|Ф|Т|А|У|Р) #REQUIRED>

]>
<university name="НИЯУ МИ_ФИ">
    <faculty name="KиБ">
        <department group_prefix="К" number="36" name="Информационные системы и технологии">
            <group number="1" entering="2010">
                <student name="Мельник Леонид" />
                <student name="Рыбников Виталий"/>
                <student name="Толстов Дмитрий"/>
                <student name="Ухоботова Ольга"/>
                <student name="Бузанова Виктория"/>
                <student name="Овчинников Игорь"/>
                <student name="Казымова Юля"/>
            </group>
        </department>
    </faculty>

    <faculty name="Ф">
    </faculty>

    <faculty name="Т">
    </faculty>

    <faculty name="А">
    </faculty>
</university>
